global using BuildingBlocks.Application.Contracts.Mediator;
global using BuildingBlocks.Application.Contracts.Repositories;
global using BuildingBlocks.Application.Contracts.Services;
global using BuildingBlocks.Application.Exceptions;
global using BuildingBlocks.Application.Validators;
global using BuildingBlocks.Application.Wrappers;
global using FluentValidation;
global using Offers.Application.Constants;
global using Offers.Application.Contracts;
global using Offers.Application.Models.DataAccess;
global using Offers.Domain;
global using Offers.Domain.ValueTypes;
global using Serilog;
global using static Offers.Application.Handlers.AddGardenOfferItemHandler;
global using static Offers.Application.Handlers.CompleteOfferHandler;
global using static Offers.Application.Handlers.CreateGardenOfferHandler;