global using BuildingBlocks.Domain.Abstractions;
global using BuildingBlocks.Domain.Entities;
global using BuildingBlocks.Domain.Exceptions;
global using BuildingBlocks.Domain.Time;
global using BuildingBlocks.Domain.ValueObjects;
global using Panels.Domain.Contractors.Entities;
global using Panels.Domain.Contractors.ValueObjects;
global using Panels.Domain.Contractors.ValueTypes;
global using Panels.Domain.Contractors.Exceptions;