version: "3.4"

networks:
  gardenapp-network:
    name: gardenapp_network

services: 
  pgadmin:
    container_name: gardenapp_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
        - postgresql
    ports:
        - "8077:80"
    environment:
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
    networks:
      - gardenapp-network
        
  postgresql:
    container_name: gardenapp_postgres
    image: postgres
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgre
        POSTGRES_PASSWORD: postgre
    networks:
      - gardenapp-network

  smtp:
    container_name: gardenapp_smtp 
    image: rnwood/smtp4dev
    restart: unless-stopped
    ports:
      - "5010:80"
      - "25:25"
    networks:
      - gardenapp-network

  seq:
    container_name: gardenapp_seq  
    image: datalust/seq
    restart: unless-stopped
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    networks:
      - gardenapp-network  