version: "3.4"

networks:
  gardenapp-network:
    name: gardenapp_network

services: 
  pgadmin:
    container_name: gardenapp_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
        - postgresql
    ports:
        - "8077:80"
    environment:
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
    networks:
      - gardenapp-network
        
  postgresql:
    container_name: gardenapp_postgres
    image: postgres
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgre
        POSTGRES_PASSWORD: postgre
    networks:
      - gardenapp-network

  smtp:
    container_name: gardenapp_smtp 
    image: rnwood/smtp4dev
    restart: unless-stopped
    ports:
      - "5010:80"
      - "25:25"
    networks:
      - gardenapp-network

  seq:
    container_name: gardenapp_seq  
    image: datalust/seq
    restart: unless-stopped
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    networks:
      - gardenapp-network  

#https://www.nathaniel-walser.com/docker-compose-templates/minio
#https://min.io/docs/minio/container/index.html

  minio:
    image: quay.io/minio/minio
    container_name: gardenapp_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - gardenapp-network   
    environment:
        # MINIO_ROOT_USER: usertest
        # MINIO_ROOT_PASSWORD: userpassword  
        MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
        MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wtrueekitnifILbZam1KYY3TG
