global using BuildingBlocks.Application.Constants;
global using BuildingBlocks.Application.Contracts.Clients.Smtp;
global using BuildingBlocks.Application.Contracts.Mediator;
global using BuildingBlocks.Application.Contracts.Repositories;
global using BuildingBlocks.Application.Exceptions;
global using BuildingBlocks.Application.Models.Clients;
global using BuildingBlocks.Application.Tools;
global using BuildingBlocks.Application.Wrappers;
global using BuildingBlocks.Domain.Exceptions;
global using BuildingBlocks.Domain.Types;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Security.Claims;
global using System.Text;
global using System.Transactions;
global using Users.Application.Constants;
global using Users.Application.Enums;
global using Users.Application.Exceptions;
global using Users.Application.Helpers;
global using Users.Application.Interfaces;
global using Users.Application.Options;
global using Users.Application.Responses;
global using Users.Application.Security;
global using Users.Application.Services;
global using Users.Application.Settings;
global using Users.Application.Templates;
global using Users.Domain.Users;
global using static Users.Application.Handlers.ConfirmUserHandler;
global using static Users.Application.Handlers.ForgotPasswordHandler;
global using static Users.Application.Handlers.LoginUserHandler;
global using static Users.Application.Handlers.RefreshTokenHandler;
global using static Users.Application.Handlers.RegisterUserHandler;
global using static Users.Application.Handlers.ResetPasswordHandler;
global using static Users.Application.Handlers.RevokeTokenHandler;
global using static Users.Application.Handlers.UserInfoHandler;