global using BuildingBlocks.Application.Contracts.Mediator;
global using BuildingBlocks.Application.Wrappers;
global using MediatR;
global using Newtonsoft.Json;
global using static Users.Application.Handlers.ForgotPasswordHandler;
global using static Users.Application.Handlers.LoginUserHandler;
global using static Users.Application.Handlers.RefreshTokenHandler;
global using static Users.Application.Handlers.RegisterUserHandler;
global using static Users.Application.Handlers.ResetPasswordHandler;
global using static Users.Application.Handlers.RevokeTokenHandler;
global using static Users.Application.Handlers.UserInfoHandler;