global using BuildingBlocks.Application.Contracts.Outbox;
global using BuildingBlocks.Application.Models.Outbox;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Newtonsoft.Json;
global using BuildingBlocks.Domain.Time;
global using Users.Infrastructure.Database;