global using BuildingBlocks.Application.Contracts.Mediator;
global using BuildingBlocks.Application.Wrappers;
global using Newtonsoft.Json;
global using Works.Application.Handlers.GardeningWork.Parameters;
global using Works.Application.Handlers.WorkItem.Parameters;
global using static Works.Application.Handlers.GardeningWork.AddGardeningWorkHandler;
global using static Works.Application.Handlers.GardeningWork.AddWorkItemHandler;
global using static Works.Application.Handlers.GardeningWork.UpdatePlannedEndDateHandler;
global using static Works.Application.Handlers.GardeningWork.UpdatePlannedStartDateHandler;
global using static Works.Application.Handlers.GardeningWork.UpdateStatusHandler;
global using static Works.Application.Handlers.WorkItem.AddTimeWeatherRecordHandler;
global using static Works.Application.Handlers.WorkItem.UpdateStatusHandler;
global using static Works.Application.Handlers.WorkItem.UpdateTimeWeatherRecordHandler;