global using BuildingBlocks.Application.Contracts.Mediator;
global using BuildingBlocks.Application.Contracts.Services;
global using BuildingBlocks.Application.Wrappers;
global using Panels.Application.Constants;
global using Panels.Application.Interfaces;
global using Panels.Domain.Contractors;
global using static Panels.Application.Handlers.Commands.AddLinkHandler;
global using static Panels.Application.Handlers.Commands.AddLogoHandler;
global using static Panels.Application.Handlers.Commands.AddProjectImageHandler;
global using static Panels.Application.Handlers.Commands.CreateNewContractorHandler;
global using static Panels.Application.Handlers.Commands.CreateProjectHandler;
global using static Panels.Application.Handlers.Commands.RemoveLinkHandler;
global using static Panels.Application.Handlers.Commands.RemoveLogoHandler;
global using static Panels.Application.Handlers.Commands.RemoveProjectHandler;
global using static Panels.Application.Handlers.Commands.RemoveProjectImageHandler;
global using static Panels.Application.Handlers.Commands.UpdateProjectDescriptionHandler;